### ISSUE TITLE
Won't compile on Android

### ISSUE THREAD

**Issue by AdamBrodzinski** [kraffslol/react-native-braintree-xplat#3]
Hello, i'm able to run this on iOS but am having issues with Android. I ran `rnpm link` and that changed some files on Android but i'm not sure what these errors are getting at. Would you have any insight on what I should try next?

**Versions**

- react-native 0.30.0
- react 15.2

**Expected:**
Android to compile with `react-native run-android`

**Actual:**
Error message:

```
:app:generateDebugSources UP-TO-DATE
:app:processDebugJavaRes UP-TO-DATE
:app:compileDebugJavaWithJavac
/Users/adam/Projects/acme/myapp-mobile/android/app/src/main/java/com/myapp/MainActivity.java:38: error: method does not override or implement a method from a supertype
    @Override
    ^
/Users/adam/Projects/acme/myapp-mobile/android/app/src/main/java/com/myapp/MainActivity.java:43: error: constructor BraintreePackage in class BraintreePackage cannot be applied to given types;
            new BraintreePackage(),
            ^
  required: Context
  found: no arguments
  reason: actual and formal argument lists differ in length
/Users/adam/Projects/acme/myapp-mobile/android/app/src/main/java/com/myapp/MainActivity.java:45: error: constructor BraintreePackage in class BraintreePackage cannot be applied to given types;
            new BraintreePackage()
            ^
  required: Context
  found: no arguments
  reason: actual and formal argument lists differ in length
3 errors
:app:compileDebugJavaWithJavac FAILED

FAILURE: Build failed with an exception.
```

My MainActivity.java file looks like:

```
package com.myapp;

import com.facebook.react.ReactActivity;
import com.oblador.vectoricons.VectorIconsPackage;
import com.pw.droplet.braintree.BraintreePackage;
import com.facebook.react.ReactPackage;
import com.facebook.react.shell.MainReactPackage;

import java.util.Arrays;
import java.util.List;

public class MainActivity extends ReactActivity {

    /**
     * Returns the name of the main component registered from JavaScript.
     * This is used to schedule rendering of the component.
     */
    @Override
    protected String getMainComponentName() {
        return "MyApp";
    }

    /**
     * Returns whether dev mode should be enabled.
     * This enables e.g. the dev menu.
     */
    @Override
    protected boolean getUseDeveloperSupport() {
        return BuildConfig.DEBUG;
    }

    /**
     * A list of packages used by the app. If the app uses additional views
     * or modules besides the default ones, add more packages here.
     */
    @Override
    protected List<ReactPackage> getPackages() {
        return Arrays.<ReactPackage>asList(
            new MainReactPackage(),
            new VectorIconsPackage(),
            new BraintreePackage()
        );
    }
}
```

I've also tried to go back to React Native `0.26` to see if that would help and it gives me less errors with:

```
:app:generateDebugSources
:app:processDebugJavaRes UP-TO-DATE
:app:compileDebugJavaWithJavac
/Users/adam/Projects/acme/myapp-mobile/android/app/src/main/java/com/myapp/MainActivity.java:41: error: constructor BraintreePackage in class BraintreePackage cannot be applied to given types;
            new BraintreePackage()
            ^
  required: Context
  found: no arguments
  reason: actual and formal argument lists differ in length
1 error
:app:compileDebugJavaWithJavac FAILED
```

Any help would be appreciated!!

**Comment by AdamBrodzinski** [comment]
Small update. I ran the example app and looked at the MainActivity file and with the changes here it works on 0.26 but not 0.30.0. Did I run `rnpm` wrong? or does it depend on a specific version?

Here's the modified file:

```
package com.tapmoney;

import com.facebook.react.ReactActivity;
import com.oblador.vectoricons.VectorIconsPackage;
import com.pw.droplet.braintree.BraintreePackage;
import com.facebook.react.ReactPackage;
import com.facebook.react.shell.MainReactPackage;

import java.util.Arrays;
import java.util.List;
import android.content.Intent;


public class MainActivity extends ReactActivity {
  private BraintreePackage mBraintreePackage;

    /**
     * Returns the name of the main component registered from JavaScript.
     * This is used to schedule rendering of the component.
     */
    @Override
    protected String getMainComponentName() {
        return "TapMoney";
    }

    /**
     * Returns whether dev mode should be enabled.
     * This enables e.g. the dev menu.
     */
    @Override
    protected boolean getUseDeveloperSupport() {
        return BuildConfig.DEBUG;
    }

    /**
     * A list of packages used by the app. If the app uses additional views
     * or modules besides the default ones, add more packages here.
     */
    @Override
    protected List<ReactPackage> getPackages() {
        return Arrays.<ReactPackage>asList(
            new MainReactPackage(),
            new VectorIconsPackage(),
            mBraintreePackage = new BraintreePackage(this)
        );
    }

    @Override
    public void onActivityResult(final int requestCode, final int resultCode, final Intent data) {
      super.onActivityResult(requestCode, resultCode, data);

      mBraintreePackage.handleActivityResult(requestCode, resultCode, data);
    }
}
```

Now with 0.30 I only get 1 error from the line `protected List<ReactPackage> getPackages()`:

```
:app:processDebugJavaRes UP-TO-DATE
:app:compileDebugJavaWithJavac
/Users/adam/Projects/acme/myapp-mobile/android/app/src/main/java/com/myapp/MainActivity.java:39: error: method does not override or implement a method from a supertype
    @Override
    ^
1 error
:app:compileDebugJavaWithJavac FAILED
```

**Comment by kraffslol** [comment]
The master branch does currently not support 0.29+ due to react native changes. I've implemented support on for 0.29+ on the 0.29-compat branch [here](https://github.com/kraffslol/react-native-braintree-xplat/tree/0.29-compat).

Please try using `"react-native-braintree-xplat": "kraffslol/react-native-braintree-xplat#0.29-compat"` in your package.json file.

You can look at the example project [here](https://github.com/kraffslol/react-native-braintree-xplat/blob/0.29-compat/example/android/app/src/main/java/com/example/MainApplication.java) to see how it's implemented.

**Comment by AdamBrodzinski** [comment]
@kraffslol awesome! thanks for all of your hard work. much appreciated! 🍻 👍 

Shall I leave this issue open for the `rnpm` issue of 0.26 not working without editing the line manually? ` mBraintreePackage = new BraintreePackage(this)` I'm not sure if that's something on the rnpm end or here (rnpm worked great on iOS though FWIW).

**Comment by kraffslol** [comment]
Yeah, keeping the issue open sounds like a good idea in case others encounter the same problem. I'll look into the rnpm problem and close the issue once the 0.29-compat branch has been merged into master.

**Comment by joelcloralt** [comment]
Hey guys, I ran into this issue so I installed the package from the `0.29-compat` branch but it won't compile. I'm getting `Braintree.java:22: error: Braintree is not abstract and does not override abstract method onNewIntent(Intent) in ActivityEventListener`

My setup is:
**/android/settings.gradle**
```
include ':react-native-braintree-xplat'
project(':react-native-braintree-xplat').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-braintree-xplat/android')
```

**/android/app/build.graddle**
```
...
dependencies {
    compile project(':react-native-braintree-xplat')
    ...
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.android.support:appcompat-v7:23.0.1"
    compile "com.facebook.react:react-native:+"
}
```

**/android/app/src/main/java/com/myproject/MainApplication.java**
```
import android.content.Intent;
import com.pw.droplet.braintree.BraintreePackage;
...
@Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          new MainReactPackage(),
          new BraintreePackage()
      );
    }
```

I'm on React Native 0.30.0:
**package.json**
```
"react": "^15.2.1",
"react-native": "^0.30.0",
"react-native-braintree-xplat": "kraffslol/react-native-braintree-xplat#0.29-compat",
```

Any ideas? 
Thanks!

**Comment by AdamBrodzinski** [comment]
@joelcloralt sorry I just bumped down to 0.26 for the time being. However, I was able to get it compiling on 0.30 by using the latest npm version and then manually editing the MainActivity file so that it removed `@Override` from the line   `protected List<ReactPackage> getPackages() {`... but I did not try it out to verify the UI worked.

**Comment by kraffslol** [comment]
@joelcloralt Seems like React Native 0.30 introduced a breaking change. I'll look into it.

**Comment by joelcloralt** [comment]
@kraffslol @AdamBrodzinski thanks for the response. I was about to post an update. I was able to compile but I'm pretty sure this is not the right solution. 

I just added this to `Braintree.java`:
```
@Override
public void onNewIntent(Intent intent){
}
```

Right now I'm dealing with the fact that `BTClient.setup(token)` is returning `Invalid Token` all the time. With the [demo token](https://developers.braintreepayments.com/start/hello-client/ios/v3#get-a-client-token) and with the token generated by my server. And this is with iOS so I don't think this hack I did is related.

**Comment by kraffslol** [comment]
@joelcloralt The token from the demo might've expired. Can you try using a token generated from [https://braintree-sample-merchant.herokuapp.com/client_token](https://braintree-sample-merchant.herokuapp.com/client_token)?

**Comment by joelcloralt** [comment]
@kraffslol I'll try that... I was using the token braintree has on their site. https://developers.braintreepayments.com/start/hello-client/ios/v3#get-a-client-token

**Comment by joelcloralt** [comment]
@kraffslol yeah I had a wrong token... I was able to initialize it and also use `BTClient.getCardNonce()`.

Let me know if you find a solution since mine is just a hack. I'm not using the drop-in UI but someone else using it might now be able to with my "solution." 

Thanks again!

**Comment by kraffslol** [comment]
@joelcloralt I think your solution is correct actually. I think it might be a good idea to add `super.onNewIntent(intent);` though. Like this:
```javascript
@Override
public void onNewIntent(Intent intent){
    super.onNewIntent(intent);
}
```
If that doesn't work your solution should be fine.

**Comment by joelcloralt** [comment]
I actually tried that and the compiler complained so I took it out. This is what it says:
```
error: cannot find symbol
    super.onNewIntent(intent);
         ^
  symbol: method onNewIntent(Intent)
```

**Comment by kraffslol** [comment]
0.29 Support has now been merged into master. Closing this issue :)

**Comment by asciiman** [comment]
```
:app:compileDebugJavaWithJavac
/Users/asciiman/Documents/Code/GoStudent/bt2/android/app/src/main/java/com/bt2/MainApplication.java:30: error: constructor BraintreePackage in class BraintreePackage cannot be applied to given types;
          new BraintreePackage()
          ^
  required: Context
  found: no arguments
  reason: actual and formal argument lists differ in length
1 error
```

Looks like this error is back again.  How to fix?

The readme says to add `new BraintreePackage()` but the constructor looks like `public BraintreePackage(Context activityContext) `.
